### ISSUE TITLE
How are questions displayed on the forum? 

### ISSUE THREAD

**Issue by lisaoshita** [shannonpileggi/SR--Oshita--iFixit#10]
Are the questions posted to the forum according to the time they were asked? Or do some questions get moved up in the forum if someone commented on it recently? I think that how visible the questions are (like if they are at the top of the forum) might play a role in how quickly they are answered.

**Comment by anthonypileggi** [comment]
Questions are sorted based on recent activity.  You can see the last action when viewing the list on https://www.ifixit.com/Answers
![screenshot 2017-07-07 13 59 20](https://user-images.githubusercontent.com/12599405/27976762-cd931364-631c-11e7-8054-c8c045db8501.png)

> I think that how visible the questions are (like if they are at the top of the forum) might play a role in how quickly they are answered.

I agree.  So when there is more activity on Answers, a question is more likely to be pushed off the first page.
