### ISSUE TITLE
reproducible descriptive stats report

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SR--Oshita--iFixit#12]
#Please start working towards making your descriptive stats report reproducible.  You can embed results from R code inline with your text.  See the snippet of code below.  This way when we get new data your descriptive stats report will automatically update.

Also, you may want to check out this tutorial for other things you can do in Rmarkdown:  http://rmarkdown.rstudio.com/lesson-1.html

The data set is cars.
```{r}
data(cars)
head(cars)
mean(cars$speed)
```

The average speed is `r mean(cars$speed)`

**Comment by lisaoshita** [comment]
Will do! Will start on this right now

**Comment by lisaoshita** [comment]
Just finished! Summary statistics, KM curves and hazard plots are in summary_stats, and individual variable exploration is in the variable_exploration file.
