### ISSUE TITLE
Reputation of the user

### ISSUE THREAD

**Issue by lisaoshita** [shannonpileggi/SR--Oshita--iFixit#14]
I'm thinking that it would be worth it to consider the reputation of the user- since you gain reputation points whenever your question/answer is up-voted, it probably motivates users to ask better questions which could get answers faster. Can you add a variable for reputation to the data? Thank you!

**Comment by anthonypileggi** [comment]
@loshita I'm going to close this because we discussed today that `new_user` is a pretty good representation of this.
