### ISSUE TITLE
Data camp courses

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SR--Oshita--iFixit#2]
Take some data camp courses to learn new R skills (listed in order of priority).

- [x] https://www.datacamp.com/courses/string-manipulation-in-r-with-stringr
- [x] https://www.datacamp.com/courses/writing-functions-in-r
- [x] https://www.datacamp.com/courses/dplyr-data-manipulation-r-tutorial
- [x] https://www.datacamp.com/courses/data-visualization-with-ggplot2-1
- [x] https://www.datacamp.com/courses/intro-to-text-mining-bag-of-words

Since the paper we posted had some machine learning topics, if you want to learn more about machine learning these courses would help give you perspective:
- [ ] https://www.datacamp.com/courses/unsupervised-learning-in-r
- [ ] https://www.datacamp.com/courses/introduction-to-machine-learning-with-r

And just for fun, if you want to learn SQL:
- [ ] https://www.datacamp.com/courses/intro-to-sql-for-data-science

**Comment by anthonypileggi** [comment]
I find that I tend to forget a lot of stuff when I breeze through these.

How about making a cheat-sheet (.Rmd) for each course as you go along, so you have a nice reference of useful functions and tools?  Then you'll still have a nice set of materials even after then DataCamp subscription expires!
