### ISSUE TITLE
device categorization

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SR--Oshita--iFixit#3]
Before you start writing code to do device categorization, think of a plan for the categorization.  How broad or specific do we want the categories to be?   For example, do you want a category for phones in general, or specifically for iphones?  Outline some options, and maybe Anthony can chime in with some ideas too.

**Comment by anthonypileggi** [comment]
You can see the category structure on iFixit.com using our API -- https://www.ifixit.com/api/2.0/doc

```r
library(data.tree)
library(tidyverse)

# Get categories from API
url <- "https://www.ifixit.com/api/2.0/categories?pretty" 
x <- jsonlite::fromJSON(url)

# Convert to a data.frame
x_clean <- x %>%
  data.tree::as.Node() %>%
  data.tree::ToDataFrameTypeCol()

# View a cool tree structure
x %>% data.tree::as.Node()

# Radial Network Plot
library(networkD3)
x %>%
    data.tree::as.Node() %>% 
    as.list(unname = TRUE, mode = "explicit") %>% 
    radialNetwork(fontSize = 12, opacity = 0.9)
```

**Comment by lisaoshita** [comment]
I'm thinking that I'll do categories for iPhone, Android, Windows, Blackberry and the Other OS Phone. I'm leaning towards categorizing the products based off of level_3 from the category structure.

**Comment by lisaoshita** [comment]
I also want to take a closer look at devices too. It looks like the way users specify the device isn't too consistent--some have "MacBook" as the device and others put a lot more detail like "MacBook Air 11" Mid 2012". I want to consider this--maybe questions that are more specific about the device get answered faster.

**Comment by shannonpileggi** [comment]
So level_3 has 227 categories.  Before you start to try to code all of that, let's think about how we would use that information to predict time until a question is answered.  Would we actually put 226 dummy variables into a Cox proportional hazards model?  Our data set is large (8000+ obs), so maybe the model could handle that many predictors.  But would it make interpretation cumbersome?  Would it improve prediction of time until answered?  I don't have an answer one way or another now, just pondering.    

I do like the idea you have of differentiating between specific and general device information.  If there is a way we could classify that that could be interesting to look at.

One more question for Anthony - is the category structure fixed, or does it get updated regularly?  If it is fixed then we can reference the structure from the API today, but if it gets updated regularly, we will want to have code that incorporates category structure as it is most up to date based on the API.

**Comment by anthonypileggi** [comment]
>  is the category structure fixed, or does it get updated regularly?

It does change as new devices are added to the site.  I would just plan on pulling it from the API occasionally.

**Comment by anthonypileggi** [comment]
> I'm leaning towards categorizing the products based off of level_3

@loshita I actually can only give you the device, level_1, and level_2 for each question.

Getting the deeper levels would require our devs to help us, which might take a few weeks/months depending on their schedule.

**Comment by lisaoshita** [comment]
I think categorizing off of level_2 should be good. I’m thinking now that the device itself might not be that significant of a predictor, but that how detailed the device name is might matter more. So I think broader categories might be fine?
