### ISSUE TITLE
When was the data downloaded?

### ISSUE THREAD

**Issue by lisaoshita** [shannonpileggi/SR--Oshita--iFixit#4]
I made the time-to-event variable, but there are quite a few NAs. I'll use the date the data was downloaded as the right-censored value for those observations.

**Comment by shannonpileggi** [comment]
Yes, that sounds good.

**Comment by anthonypileggi** [comment]
I can add a field to the data called `download_date` to indicate when it was downloaded.  I'll update the data and key in a pull request.
