### ISSUE TITLE
26 negative values in the time_until_answer variable 

### ISSUE THREAD

**Issue by lisaoshita** [shannonpileggi/SR--Oshita--iFixit#8]
All of the negative values for the time_until_answer variable correspond to questions that were answered-- so the post_date is greater than the first_answer_date. Should I filter these out of the dataset?

**Comment by anthonypileggi** [comment]
I took a look at some of those questions, and they seem to be garbage questions.  There were probably some moderator edits/deletes that messed with the original post dates.

Here's an example:  https://www.ifixit.com/Answers/View/406040/How+do+you+open+up+speaker

**I'll remove those questions in the data moving forward, so you won't have to worry about it.**

Something else to keep in mind is that you can check out the questions on our website yourself.  Just append the `id` of the question you want to view -- https://www.ifixit.com/Answers/View/{id}

**Comment by anthonypileggi** [comment]
> **I'll remove those questions in the data moving forward, so you won't have to worry about it.**

Ok I did the thing!  420c6f26b559562a317c3b7d7db04c6c2fda57d6

**Comment by lisaoshita** [comment]
Thank you!
