### ISSUE TITLE
NA's in the category variable

### ISSUE THREAD

**Issue by lisaoshita** [shannonpileggi/SR--Oshita--iFixit#9]
In the out dataframe, there are 2022 NAs in the category variable (out of the 8089). How should I work with this? Also, is it okay if I subset the data to only deal with observations in English?

**Comment by anthonypileggi** [comment]
NAs occur when users create a question for a device that does not already exist on our website.  We have a device auto-fill, but users don't always use it.
![screenshot 2017-07-07 07 40 13](https://user-images.githubusercontent.com/12599405/27962691-89ac300c-62e7-11e7-9094-567242e26cd3.png)

We also have some "orphan" devices -- i.e., devices without categorization.  Our tech writers try to categorize them as the come up, but there are still quite a few orphan devices.

Maybe just call all the NAs "Other" for now?  I guess it ultimately depends on how you plan to use the category data.
